package concesionariojava;

public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        añadirCoche = new javax.swing.JFrame();
        jLabel16 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        coches = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbMarcaMain = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cbMotorMain = new javax.swing.JComboBox<>();
        cbBuscarMain = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        txtBuscarMain = new javax.swing.JTextField();
        btnBuscarMain = new javax.swing.JButton();
        btnReiniciarBusqueda = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaMain = new javax.swing.JTable();
        btnVentaNueva = new javax.swing.JButton();
        btnRevisionNueva = new javax.swing.JButton();
        btnCocheBorrar = new javax.swing.JButton();
        btnCocheModificar = new javax.swing.JButton();
        btnCocheNuevo = new javax.swing.JButton();
        revisiones = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaRevisiones = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblNumeroRevisionMain = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblFechaRevisionMain = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblBastidorRevisionMain = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblMarcaRevisionMain = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblModeloRevisionMain = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblFrenosRevisionMain = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lblFiltroRevisionMain = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        lblAceiteRevisionMain = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        pImagenRevisionMain = new javax.swing.JPanel();
        btnRevisionBorrar = new javax.swing.JButton();
        btnRevisionModificar = new javax.swing.JButton();
        ventas = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tablaVentas = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        lblFechaVentaMain = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblNombreVentaMain = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblApellidosVentaMain = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lblDniVentaMain = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        lblCocheVentaMain = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        lblPrecioVentaMain = new javax.swing.JLabel();
        btnVentaBorrar = new javax.swing.JButton();
        btnVentaModificar = new javax.swing.JButton();
        clientes = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaClientes = new javax.swing.JList<>();
        jLabel12 = new javax.swing.JLabel();
        lblDniClienteMain = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        lblNombreClienteMain = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        lblApellidosClienteMain = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        lblTelefonoClienteMain = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        lblDireccionClienteMain = new javax.swing.JLabel();
        btnClienteBorrar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        menu = new javax.swing.JMenuBar();
        archivo = new javax.swing.JMenu();
        reiniciarbd = new javax.swing.JMenuItem();
        salir = new javax.swing.JMenuItem();
        ayuda = new javax.swing.JMenu();
        acercade = new javax.swing.JMenuItem();
        manual = new javax.swing.JMenuItem();

        añadirCoche.setTitle("Añadir coche");

        jLabel16.setText("Nº BASTIDOR");

        jLabel23.setText("MODELO");

        jTextField2.setText("jTextField2");

        jLabel26.setText("MOTOR");

        jTextField3.setText("jTextField3");

        jLabel28.setText("COLOR");

        jTextField4.setText("jTextField4");

        javax.swing.GroupLayout añadirCocheLayout = new javax.swing.GroupLayout(añadirCoche.getContentPane());
        añadirCoche.getContentPane().setLayout(añadirCocheLayout);
        añadirCocheLayout.setHorizontalGroup(
            añadirCocheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(añadirCocheLayout.createSequentialGroup()
                .addGroup(añadirCocheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(añadirCocheLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel16))
                    .addGroup(añadirCocheLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(añadirCocheLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel23))
                    .addGroup(añadirCocheLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(añadirCocheLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel26))
                    .addGroup(añadirCocheLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(añadirCocheLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel28))
                    .addGroup(añadirCocheLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(265, Short.MAX_VALUE))
        );
        añadirCocheLayout.setVerticalGroup(
            añadirCocheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(añadirCocheLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel16)
                .addGap(8, 8, 8)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Concesionario");
        setResizable(false);

        jLabel1.setText("Filtro:");

        jLabel2.setText("Marca");

        cbMarcaMain.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Motor");

        cbMotorMain.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbBuscarMain.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        txtBuscarMain.setToolTipText("");

        btnBuscarMain.setText("Buscar");

        btnReiniciarBusqueda.setText("Reiniciar Búsqueda");

        tablaMain.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaMain);
        if (tablaMain.getColumnModel().getColumnCount() > 0) {
            tablaMain.getColumnModel().getColumn(0).setResizable(false);
            tablaMain.getColumnModel().getColumn(1).setResizable(false);
            tablaMain.getColumnModel().getColumn(2).setResizable(false);
            tablaMain.getColumnModel().getColumn(3).setResizable(false);
        }

        btnVentaNueva.setText("VENTA");

        btnRevisionNueva.setText("REVISIÓN");

        btnCocheBorrar.setText("ELIMINAR");

        btnCocheModificar.setText("MODIFICAR");

        btnCocheNuevo.setText("NUEVO");

        javax.swing.GroupLayout cochesLayout = new javax.swing.GroupLayout(coches);
        coches.setLayout(cochesLayout);
        cochesLayout.setHorizontalGroup(
            cochesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cochesLayout.createSequentialGroup()
                .addGroup(cochesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cochesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(cochesLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(cochesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cochesLayout.createSequentialGroup()
                                .addComponent(btnVentaNueva, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addComponent(btnRevisionNueva, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCocheNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addComponent(btnCocheModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addComponent(btnCocheBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(cochesLayout.createSequentialGroup()
                                .addGroup(cochesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(cochesLayout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel2)
                                        .addGap(8, 8, 8)
                                        .addComponent(cbMarcaMain, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel3)
                                        .addGap(8, 8, 8)
                                        .addComponent(cbMotorMain, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(8, 8, 8)
                                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(8, 8, 8)
                                        .addComponent(cbBuscarMain, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtBuscarMain, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnBuscarMain))
                                    .addComponent(btnReiniciarBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 60, Short.MAX_VALUE)))))
                .addGap(8, 8, 8))
        );
        cochesLayout.setVerticalGroup(
            cochesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cochesLayout.createSequentialGroup()
                .addGroup(cochesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cochesLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(cochesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(cbMarcaMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(cbMotorMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbBuscarMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBuscarMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscarMain))
                        .addGap(12, 12, 12)
                        .addComponent(btnReiniciarBusqueda))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(cochesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVentaNueva)
                    .addComponent(btnRevisionNueva)
                    .addComponent(btnCocheBorrar)
                    .addComponent(btnCocheModificar)
                    .addComponent(btnCocheNuevo))
                .addGap(8, 8, 8))
        );

        jTabbedPane1.addTab("COCHES", null, coches, "");

        listaRevisiones.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(listaRevisiones);

        jLabel4.setText("Nº REVISIÓN");

        jLabel5.setText("Nº REVISIÓN");

        lblNumeroRevisionMain.setText("1");
        lblNumeroRevisionMain.setToolTipText("");

        jLabel7.setText("FECHA");

        lblFechaRevisionMain.setText("2017/12/04");

        jLabel9.setText("Nº BASTIDOR");

        lblBastidorRevisionMain.setText("ABC12345678909876");

        jLabel11.setText("MARCA");

        lblMarcaRevisionMain.setText("NISSAN");

        jLabel13.setText("MODELO");

        lblModeloRevisionMain.setText("PRIMERA");

        jLabel15.setText("REVISIÓN DE FRENOS:");

        lblFrenosRevisionMain.setText("SÍ");

        jLabel17.setText("CAMBIO DE FILTRO:");

        lblFiltroRevisionMain.setText("SÍ");

        jLabel19.setText("CAMBIO DE ACEITE:");

        lblAceiteRevisionMain.setText("SÍ");

        jLabel21.setText("IMAGEN");

        pImagenRevisionMain.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout pImagenRevisionMainLayout = new javax.swing.GroupLayout(pImagenRevisionMain);
        pImagenRevisionMain.setLayout(pImagenRevisionMainLayout);
        pImagenRevisionMainLayout.setHorizontalGroup(
            pImagenRevisionMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );
        pImagenRevisionMainLayout.setVerticalGroup(
            pImagenRevisionMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );

        btnRevisionBorrar.setText("ELIMINAR");

        btnRevisionModificar.setText("MODIFICAR");

        javax.swing.GroupLayout revisionesLayout = new javax.swing.GroupLayout(revisiones);
        revisiones.setLayout(revisionesLayout);
        revisionesLayout.setHorizontalGroup(
            revisionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(revisionesLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(revisionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(revisionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(revisionesLayout.createSequentialGroup()
                        .addGroup(revisionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(revisionesLayout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblAceiteRevisionMain)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 310, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, revisionesLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnRevisionModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)))
                        .addComponent(btnRevisionBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel13)
                    .addGroup(revisionesLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblFrenosRevisionMain))
                    .addGroup(revisionesLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblFiltroRevisionMain))
                    .addGroup(revisionesLayout.createSequentialGroup()
                        .addGroup(revisionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5)
                            .addComponent(jLabel9)
                            .addComponent(lblBastidorRevisionMain, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .addComponent(lblNumeroRevisionMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblModeloRevisionMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(48, 48, 48)
                        .addGroup(revisionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7)
                            .addComponent(jLabel11)
                            .addComponent(lblFechaRevisionMain, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                            .addComponent(lblMarcaRevisionMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(29, 29, 29)
                        .addGroup(revisionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(pImagenRevisionMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(8, 8, 8))
        );
        revisionesLayout.setVerticalGroup(
            revisionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(revisionesLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(revisionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel21))
                .addGap(8, 8, 8)
                .addGroup(revisionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(revisionesLayout.createSequentialGroup()
                        .addGroup(revisionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(revisionesLayout.createSequentialGroup()
                                .addGroup(revisionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblNumeroRevisionMain)
                                    .addComponent(lblFechaRevisionMain))
                                .addGap(24, 24, 24)
                                .addGroup(revisionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel11))
                                .addGap(8, 8, 8)
                                .addGroup(revisionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblBastidorRevisionMain)
                                    .addComponent(lblMarcaRevisionMain))
                                .addGap(24, 24, 24)
                                .addComponent(jLabel13)
                                .addGap(8, 8, 8)
                                .addComponent(lblModeloRevisionMain))
                            .addComponent(pImagenRevisionMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(revisionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(lblFrenosRevisionMain))
                        .addGap(8, 8, 8)
                        .addGroup(revisionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(lblFiltroRevisionMain))))
                .addGroup(revisionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(revisionesLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(revisionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(lblAceiteRevisionMain))
                        .addContainerGap(38, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, revisionesLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(revisionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRevisionBorrar)
                            .addComponent(btnRevisionModificar))
                        .addGap(8, 8, 8))))
        );

        jTabbedPane1.addTab("REVISIONES", null, revisiones, "");

        tablaVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nº BASTIDOR", "DNI"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tablaVentas);

        jLabel6.setText("FECHA");

        lblFechaVentaMain.setText("2017/12/04");

        jLabel10.setText("NOMBRE");

        lblNombreVentaMain.setText("Juan Carlos");

        jLabel14.setText("APELLIDOS");

        lblApellidosVentaMain.setText("Expósito Romero");

        jLabel18.setText("DNI");

        lblDniVentaMain.setText("05983762J");

        jLabel22.setText("COCHE");

        lblCocheVentaMain.setText("NISSAN PRIMERA");

        jLabel24.setText("PRECIO");

        lblPrecioVentaMain.setText("1500.0");

        btnVentaBorrar.setText("ELIMINAR");

        btnVentaModificar.setText("MODIFICAR");

        javax.swing.GroupLayout ventasLayout = new javax.swing.GroupLayout(ventas);
        ventas.setLayout(ventasLayout);
        ventasLayout.setHorizontalGroup(
            ventasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventasLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(ventasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel18)
                    .addGroup(ventasLayout.createSequentialGroup()
                        .addGroup(ventasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblFechaVentaMain, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDniVentaMain, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCocheVentaMain, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(lblNombreVentaMain, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(48, 48, 48)
                        .addGroup(ventasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(jLabel14)
                            .addComponent(lblApellidosVentaMain, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPrecioVentaMain, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(195, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ventasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVentaModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(btnVentaBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );
        ventasLayout.setVerticalGroup(
            ventasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventasLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(ventasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ventasLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblFechaVentaMain)
                        .addGap(18, 18, 18)
                        .addGroup(ventasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ventasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombreVentaMain)
                            .addComponent(lblApellidosVentaMain))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDniVentaMain)
                        .addGap(18, 18, 18)
                        .addGroup(ventasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(jLabel24))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ventasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCocheVentaMain)
                            .addComponent(lblPrecioVentaMain)))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(ventasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVentaBorrar)
                    .addComponent(btnVentaModificar))
                .addGap(8, 8, 8))
        );

        jTabbedPane1.addTab("VENTAS", null, ventas, "");

        jLabel8.setText("DNI");

        listaClientes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(listaClientes);

        jLabel12.setText("DNI");

        lblDniClienteMain.setText("05983762J");

        jLabel20.setText("Nombre");

        lblNombreClienteMain.setText("Juan Carlos");

        jLabel25.setText("Apellidos");

        lblApellidosClienteMain.setText("Expósito Romero");

        jLabel27.setText("Teléfono");

        lblTelefonoClienteMain.setText("722256261");

        jLabel29.setText("Dirección");

        lblDireccionClienteMain.setText("Poro 3, Torrecampo, Córdoba");

        btnClienteBorrar.setText("ELIMINAR");

        jButton2.setText("MODIFICAR");

        javax.swing.GroupLayout clientesLayout = new javax.swing.GroupLayout(clientes);
        clientes.setLayout(clientesLayout);
        clientesLayout.setHorizontalGroup(
            clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientesLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(47, 47, 47)
                .addGroup(clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12)
                    .addGroup(clientesLayout.createSequentialGroup()
                        .addGroup(clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(clientesLayout.createSequentialGroup()
                                .addComponent(lblNombreClienteMain, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                                .addGap(48, 48, 48))
                            .addGroup(clientesLayout.createSequentialGroup()
                                .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(48, 48, 48)))
                        .addGroup(clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addComponent(lblApellidosClienteMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel27)
                    .addComponent(jLabel29)
                    .addComponent(lblDireccionClienteMain, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDniClienteMain, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelefonoClienteMain, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(283, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, clientesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(btnClienteBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );
        clientesLayout.setVerticalGroup(
            clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientesLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel12))
                .addGroup(clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(clientesLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(clientesLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDniClienteMain)
                        .addGap(18, 18, 18)
                        .addGroup(clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(jLabel25))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombreClienteMain)
                            .addComponent(lblApellidosClienteMain))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTelefonoClienteMain)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDireccionClienteMain)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClienteBorrar)
                    .addComponent(jButton2))
                .addGap(8, 8, 8))
        );

        jTabbedPane1.addTab("CLIENTES", null, clientes, "");

        archivo.setText("Archivo");

        reiniciarbd.setText("Reiniciar BBDD");
        reiniciarbd.setToolTipText("");
        archivo.add(reiniciarbd);

        salir.setText("Salir");
        salir.setToolTipText("");
        archivo.add(salir);

        menu.add(archivo);

        ayuda.setText("Ayuda");
        ayuda.setToolTipText("");

        acercade.setText("Acerca de");
        acercade.setToolTipText("");
        ayuda.add(acercade);

        manual.setText("Manual");
        manual.setToolTipText("");
        ayuda.add(manual);

        menu.add(ayuda);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem acercade;
    private javax.swing.JMenu archivo;
    private javax.swing.JMenu ayuda;
    private javax.swing.JFrame añadirCoche;
    private javax.swing.JButton btnBuscarMain;
    private javax.swing.JButton btnClienteBorrar;
    private javax.swing.JButton btnCocheBorrar;
    private javax.swing.JButton btnCocheModificar;
    private javax.swing.JButton btnCocheNuevo;
    private javax.swing.JButton btnReiniciarBusqueda;
    private javax.swing.JButton btnRevisionBorrar;
    private javax.swing.JButton btnRevisionModificar;
    private javax.swing.JButton btnRevisionNueva;
    private javax.swing.JButton btnVentaBorrar;
    private javax.swing.JButton btnVentaModificar;
    private javax.swing.JButton btnVentaNueva;
    private javax.swing.JComboBox<String> cbBuscarMain;
    private javax.swing.JComboBox<String> cbMarcaMain;
    private javax.swing.JComboBox<String> cbMotorMain;
    private javax.swing.JPanel clientes;
    private javax.swing.JPanel coches;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel lblAceiteRevisionMain;
    private javax.swing.JLabel lblApellidosClienteMain;
    private javax.swing.JLabel lblApellidosVentaMain;
    private javax.swing.JLabel lblBastidorRevisionMain;
    private javax.swing.JLabel lblCocheVentaMain;
    private javax.swing.JLabel lblDireccionClienteMain;
    private javax.swing.JLabel lblDniClienteMain;
    private javax.swing.JLabel lblDniVentaMain;
    private javax.swing.JLabel lblFechaRevisionMain;
    private javax.swing.JLabel lblFechaVentaMain;
    private javax.swing.JLabel lblFiltroRevisionMain;
    private javax.swing.JLabel lblFrenosRevisionMain;
    private javax.swing.JLabel lblMarcaRevisionMain;
    private javax.swing.JLabel lblModeloRevisionMain;
    private javax.swing.JLabel lblNombreClienteMain;
    private javax.swing.JLabel lblNombreVentaMain;
    private javax.swing.JLabel lblNumeroRevisionMain;
    private javax.swing.JLabel lblPrecioVentaMain;
    private javax.swing.JLabel lblTelefonoClienteMain;
    private javax.swing.JList<String> listaClientes;
    private javax.swing.JList<String> listaRevisiones;
    private javax.swing.JMenuItem manual;
    private javax.swing.JMenuBar menu;
    private javax.swing.JPanel pImagenRevisionMain;
    private javax.swing.JMenuItem reiniciarbd;
    private javax.swing.JPanel revisiones;
    private javax.swing.JMenuItem salir;
    private javax.swing.JTable tablaMain;
    private javax.swing.JTable tablaVentas;
    private javax.swing.JTextField txtBuscarMain;
    private javax.swing.JPanel ventas;
    // End of variables declaration//GEN-END:variables
}
